# ===================================================================
# CONFIGURACIÓN GENERAL DEL ENTORNO DE EJECUCIÓN - KINALAPP
# ===================================================================
server.port=8080
# Puerto de escucha asignado por defecto para el contenedor embebido Tomcat
# =========================================
# CONFIGURACIÓN MYSQL
# =========================================

# Protocolo JDBC para la persistencia en el servidor MySQL local
spring.datasource.url=jdbc:mysql://localhost:3306/kinalapp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# Credenciales de autenticación del DataSource administrado por HikariCP
spring.datasource.username=root
spring.datasource.password=*jeshua1234567
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# =========================================
# JPA / HIBERNATE
# =========================================
# Parámetros de auditoría para el análisis de sentencias SQL generadas
spring.jpa.hibernate.ddl-auto=update
# Estrategia de sincronización estructural automática entre entidades y tablas de MySQL
spring.jpa.show-sql=true
# Salida estandarizada de logs para el monitoreo de operaciones CRUD
spring.jpa.properties.hibernate.format_sql=true
# Indentación visual de código SQL embebido para facilitar la lectura en la consola
# Seteos finales aprobados para el bloque de base de datos relacional
# =========================================
# THYMELEAF
# =========================================
spring.thymeleaf.cache=false
# Parámetros adicionales de serialización y codificación de respuestas

# Parametros adicionales de serializacion y codificacion de respuestas
# =========================================
# MOSTRAR ERRORES
# =========================================
server.error.include-message=always
server.error.include-binding-errors=always

# Fin del segmento de orquestación de datos e infraestructura persistente