# ===================================================================
# CONFIGURACIÓN GENERAL DEL ENTORNO DE EJECUCIÓN - KINALAPP
# ===================================================================
server.port=8080
# Puerto de escucha asignado por defecto para el contenedor embebido Tomcat
# =========================================
# CONFIGURACIÓN MYSQL
# =========================================

# Protocolo JDBC para la persistencia en el servidor MySQL local
spring.datasource.url=jdbc:mysql://localhost:3306/kinalapp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=*jeshua1234567
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# =========================================
# JPA / HIBERNATE
# =========================================
# Parámetros de auditoría para el análisis de sentencias SQL generadas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# =========================================
# THYMELEAF
# =========================================
spring.thymeleaf.cache=false
# Parámetros adicionales de serialización y codificación de respuestas
# =========================================
# MOSTRAR ERRORES
# =========================================
server.error.include-message=always
server.error.include-binding-errors=always